server:
  port: 8056
  servlet:
    context-path: /api

spring:
  application:
    name: calculate

app:
  cors:
    allowed-origins: "http://localhost:4200"

logging:
  level:
    root: INFO
    de.osetrov.calculate: DEBUG
